function [estimation_result] = make_estimation_simulation( ...
    simulation_count, model, true_params, params_opt_set, ...
    trajectory_length, solver, result_handler...
    )
    estimation_result = EstimationSimulationResult(simulation_count, size(true_params, 2));

    for sim_index = 1:simulation_count
        trajectory = model.generate_trajectory( ...
            true_params, trajectory_length ...
        );
        estimates = compute_max_likelihood_estimator(trajectory, model, ...
            params_opt_set, solver ...
        );
        estimation_result.add_new_estimate(estimates);

        if all(size(result_handler) == [1, 1])
            result_handler(estimation_result) %% TODO: implemend SaveHandler
        end
    end
end

