function [estimation_result] = make_estimation_simulation( ...
    simulation_count, model, true_params, params_opt_set, ...
    trajectory_length, compute_estimates, solver, result_handler, num_handles...
    )

    estimation_result = EstimationSimulationResult(simulation_count, size(true_params, 2));
    
    for sim_index = 1:simulation_count
        trajectory = model.generate_trajectory( ...
            true_params, trajectory_length ...
        );
        estimates = compute_estimates(trajectory, model, ...
            params_opt_set, solver ...
        );
        estimation_result.add_new_estimate(estimates);

        if ~isempty(result_handler) && ...
                simulation_count >= 2 * num_handles && ...
                mod(sim_index, floor(simulation_count / num_handles)) == 0
            result_handler.handle(estimation_result)
        end
    end
   
    if ~isempty(result_handler)
        result_handler.handle(estimation_result);
    end
end

